name: Deploy Escalation-Matrix-Countdown to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # New step to automatically change the base path for deployment
      - name: Rewrite base href for GitHub Pages
        run: sed -i 's/<base href="\/" \/>/<base href="\/Escalation-Matrix-Countdown\/" \/>/' wwwroot/index.html

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Publish .NET Project
        run: dotnet publish EscalationMatrixCountdown.csproj -c Release -o release --nologo

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'release/wwwroot'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4